# Generated by Django 5.0.14 on 2025-09-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academ',
            table='Academ',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='Attendance',
        ),
        migrations.AlterModelTable(
            name='courseprojects',
            table='Course_projects',
        ),
        migrations.AlterModelTable(
            name='debtaudit',
            table='Debt_audit',
        ),
        migrations.AlterModelTable(
            name='debts',
            table='Debts',
        ),
        migrations.AlterModelTable(
            name='diploma',
            table='Diploma',
        ),
        migrations.AlterModelTable(
            name='disciples',
            table='Disciples',
        ),
        migrations.AlterModelTable(
            name='educationplan',
            table='Education_plan',
        ),
        migrations.AlterModelTable(
            name='formcontrol',
            table='Form_Control',
        ),
        migrations.AlterModelTable(
            name='grades',
            table='Grades',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='nagruzka',
            table='Nagruzka',
        ),
        migrations.AlterModelTable(
            name='practise',
            table='Practise',
        ),
        migrations.AlterModelTable(
            name='practisetype',
            table='Practise_type',
        ),
        migrations.AlterModelTable(
            name='ratingtype',
            table='Rating_type',
        ),
        migrations.AlterModelTable(
            name='specialty',
            table='Specialty',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='Teachers',
        ),
    ]
