# Generated by Django 5.0.14 on 2025-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_academ_table_alter_attendance_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID дисциплины')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID факультета')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'db_table': 'faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID результата')),
                ('result_value', models.CharField(max_length=50, verbose_name='Значение результата')),
            ],
            options={
                'verbose_name': 'Тип результата',
                'verbose_name_plural': 'Типы результатов',
                'db_table': 'result_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'db_table': 'speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'db_table': 'student_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Результат студента',
                'verbose_name_plural': 'Результаты студентов',
                'db_table': 'student_result',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Academ',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='CourseProjects',
        ),
        migrations.DeleteModel(
            name='DebtAudit',
        ),
        migrations.DeleteModel(
            name='Debts',
        ),
        migrations.DeleteModel(
            name='Diploma',
        ),
        migrations.DeleteModel(
            name='Disciples',
        ),
        migrations.DeleteModel(
            name='EducationPlan',
        ),
        migrations.DeleteModel(
            name='FormControl',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='HoursPerSemest',
        ),
        migrations.DeleteModel(
            name='Nagruzka',
        ),
        migrations.DeleteModel(
            name='Practise',
        ),
        migrations.DeleteModel(
            name='PractiseType',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingType',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
