# Generated by Django 5.0.14 on 2025-11-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_discipline_faculty_resulttype_speciality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'verbose_name': 'Результат студента', 'verbose_name_plural': 'Результаты студентов'},
        ),
    ]
