# Generated by Django 5.0.14 on 2025-11-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_studentresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'managed': False, 'verbose_name': 'Результат студента', 'verbose_name_plural': 'Результаты студентов'},
        ),
    ]
