# Generated by Django 5.2.8 on 2026-01-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_attendance_options_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson_id', 'student')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_value_of_sertificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.AddField(
            model_name='attendance',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson_id',
            field=models.IntegerField(default=1, verbose_name='ID занятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.student', verbose_name='Студент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.faculty', verbose_name='Факультет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.TextField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.studentgroup', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_academic',
            field=models.BooleanField(default=False, verbose_name='В академическом отпуске'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.speciality', verbose_name='Специальность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.discipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='result',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='application.resulttype', verbose_name='Результат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.student', verbose_name='Студент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID студента'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student', 'discipline')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
